---
abstract: 'Display HTML snippets in user-controllable, savable order'
author:
  - "'Zoffix <'zoffix@cpan.org'>"
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ZofCMS-Plugin-PreferentialOrder
provides:
  App::ZofCMS::Plugin::PreferentialOrder:
    file: lib/App/ZofCMS/Plugin/PreferentialOrder.pm
    version: 0.0102
requires:
  App::ZofCMS::Plugin::Base: 0.0106
  DBI: 1.607
  HTML::Template: 2.9
resources:
  license: http://dev.perl.org/licenses/
version: 0.0102
